In [1]:
import tensorflow as tf
import keras
import numpy as np

Using Theano backend.


In [3]:
data_in = np.array([[0,0],[0,1],[1,0],[1,1]])
print (data_in)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [4]:
logic_and = np.array([[0],[0],[0],[1]])
logic_or = np.array([[0],[1],[1],[1]])
logic_xor = np.array([[0],[1],[1],[0]])

In [14]:
#single perceptron for AND and OR
model = keras.models.Sequential(layers=[
    keras.layers.Dense(input_dim=2, units=1),
    keras.layers.Activation(keras.activations.sigmoid)
])
model.compile(optimizer=keras.optimizers.SGD(lr=0.5), loss='mse' )

In [15]:
#multipllayer perceptron for XOR
model_xor = keras.models.Sequential(layers=[
    keras.layers.Dense(input_dim=2, units=2),
    keras.layers.Activation(keras.activations.sigmoid),
    keras.layers.Dense(units=1),
    keras.layers.Activation(keras.activations.sigmoid)
])

model_xor.compile(optimizer=keras.optimizers.SGD(lr=0.5), loss='mse' )

In [16]:
print (keras.backend.eval(model_xor.weights[0])) #weights layer1
print (keras.backend.eval(model_xor.weights[1])) #bias
print (keras.backend.eval(model_xor.weights[2])) #weights layer2
print (keras.backend.eval(model_xor.weights[3])) #bias

[[-0.51886934  1.21101582]
 [-0.2389825   0.34911227]]
[ 0.  0.]
[[ 0.12827718]
 [ 0.56995821]]
[ 0.]


In [20]:
model_xor.fit(data_in, logic_xor, epochs =10000, verbose=False)

In [21]:
print (model_xor.predict(np.array([[0,0]])))
print (model_xor.predict(np.array([[0,1]])))
print (model_xor.predict(np.array([[1,0]])))
print (model_xor.predict(np.array([[1,1]])))

[[ 0.00938519]]
[[ 0.9919076]]
[[ 0.99191016]]
[[ 0.00967643]]
