In [276]:
import numpy as np
import scipy

In [277]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])

Y_AND = np.array([0,0,0,1]).reshape((4,1))
Y_OR = np.array([0,1,1,1]).reshape((4,1))
Y_XOR = np.array([0,1,1,0]).reshape((4,1))
Y_EXNOR = np.array([1,0,0,1]).reshape((4,1))

print ("X is \n {} \n its shape is {}". format(X,X.shape))
print ("Y_AND is \n {} \n its shape is {}".format(Y_AND,Y_AND.shape))
print ("Y_OR is \n {} \n its shape is {}".format(Y_OR,Y_OR.shape))
print ("Y_XOR is \n {} \n its shape is {}".format(Y_XOR,Y_XOR.shape))
print ("Y_EXNOR is \n {} \n its shape is {}".format(Y_EXNOR,Y_EXNOR.shape))

X is 
 [[0 0]
 [0 1]
 [1 0]
 [1 1]] 
 its shape is (4, 2)
Y_AND is 
 [[0]
 [0]
 [0]
 [1]] 
 its shape is (4, 1)
Y_OR is 
 [[0]
 [1]
 [1]
 [1]] 
 its shape is (4, 1)
Y_XOR is 
 [[0]
 [1]
 [1]
 [0]] 
 its shape is (4, 1)
Y_EXNOR is 
 [[1]
 [0]
 [0]
 [1]] 
 its shape is (4, 1)


In [278]:
#weights initialization
def init_weights():
    W = np.random.randn(1,2)
    #W = np.zeros((1,2))
    b = 0
    return W, b

In [282]:
# example for implementation of step function
# unit_step = lambda x: 0 if x < 0 else 1
def heaviside_step_function(n):
    """Return the value of the Heaviside step function of `n`.

    Parameters
    ----------
    n : float
        The number of which the Heaviside step function should be computed.

    Returns
    -------
    int
        The value of the Heaviside step function of `n`.

    """
    if n < 0:
        res = 0
    else:
        res = 1
    return res



In [289]:
#for example
sample_list = np.array([1.0, -3, 1, 4.3, -1, 0.1, 1.2]).reshape((1,7))
print sample_list
print np.heaviside(sample_list,)
#for i in sample_list:
#    print (heaviside_step_function(i))

[[ 1.  -3.   1.   4.3 -1.   0.1  1.2]]
[[ 1.  0.  1.  1.  0.  1.  1.]]


In [68]:
# propagate function returns error
def propagate(W,b,X,Y):
    A = np.heaviside((np.dot(X,W.T) + b), b)
    Error = Y - A
    return Error


In [77]:
W, b = init_weights()
print W 
print b
#print(propagate(W,b,X,Y_OR))

[[-0.46696933  0.7469459 ]]
0


In [81]:
def optimize(W,b,X,Y,num_iterations, learning_rate):
    
    for i in range(num_iterations):
        Error = propagate(W,b,X,Y)
        print ("Error is {} for iteration {}".format(Error, i+1))
        W = W + np.multiply(learning_rate , (np.dot(Error.T,X))) 
        b = b + np.multiply(learning_rate , Error)
        print ("W is {}".format(W))
        print ("b is {}".format(W))
    params = {"W" : W, "b" : b}
    
    return params

print optimize(W,b,X,Y_XOR,1000,0.001)       

Error is [[ 0.]
 [ 0.]
 [ 1.]
 [-1.]] for iteration 1
W is [[-0.46696933  0.7459459 ]]
b is [[-0.46696933  0.7459459 ]]
Error is [[ 0.]
 [ 0.]
 [ 1.]
 [-1.]] for iteration 2
W is [[-0.46696933  0.7449459 ]]
b is [[-0.46696933  0.7449459 ]]
Error is [[ 0.]
 [ 0.]
 [ 1.]
 [-1.]] for iteration 3
W is [[-0.46696933  0.7439459 ]]
b is [[-0.46696933  0.7439459 ]]
Error is [[ 0.]
 [ 0.]
 [ 1.]
 [-1.]] for iteration 4
W is [[-0.46696933  0.7429459 ]]
b is [[-0.46696933  0.7429459 ]]
Error is [[ 0.]
 [ 0.]
 [ 1.]
 [-1.]] for iteration 5
W is [[-0.46696933  0.7419459 ]]
b is [[-0.46696933  0.7419459 ]]
Error is [[ 0.]
 [ 0.]
 [ 1.]
 [-1.]] for iteration 6
W is [[-0.46696933  0.7409459 ]]
b is [[-0.46696933  0.7409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 1.]
 [-1.]] for iteration 7
W is [[-0.46696933  0.7399459 ]]
b is [[-0.46696933  0.7399459 ]]
Error is [[ 0.]
 [ 0.]
 [ 1.]
 [-1.]] for iteration 8
W is [[-0.46696933  0.7389459 ]]
b is [[-0.46696933  0.7389459 ]]
Error is [[ 0.]
 [ 0.]
 [ 1.]
 [-1.]] fo

 [-1.]] for iteration 128
W is [[-0.46696933  0.6189459 ]]
b is [[-0.46696933  0.6189459 ]]
Error is [[ 0.]
 [ 0.]
 [ 1.]
 [-1.]] for iteration 129
W is [[-0.46696933  0.6179459 ]]
b is [[-0.46696933  0.6179459 ]]
Error is [[ 0.]
 [ 0.]
 [ 1.]
 [-1.]] for iteration 130
W is [[-0.46696933  0.6169459 ]]
b is [[-0.46696933  0.6169459 ]]
Error is [[ 0.]
 [ 0.]
 [ 1.]
 [-1.]] for iteration 131
W is [[-0.46696933  0.6159459 ]]
b is [[-0.46696933  0.6159459 ]]
Error is [[ 0.]
 [ 0.]
 [ 1.]
 [-1.]] for iteration 132
W is [[-0.46696933  0.6149459 ]]
b is [[-0.46696933  0.6149459 ]]
Error is [[ 0.]
 [ 0.]
 [ 1.]
 [-1.]] for iteration 133
W is [[-0.46696933  0.6139459 ]]
b is [[-0.46696933  0.6139459 ]]
Error is [[ 0.]
 [ 0.]
 [ 1.]
 [-1.]] for iteration 134
W is [[-0.46696933  0.6129459 ]]
b is [[-0.46696933  0.6129459 ]]
Error is [[ 0.]
 [ 0.]
 [ 1.]
 [-1.]] for iteration 135
W is [[-0.46696933  0.6119459 ]]
b is [[-0.46696933  0.6119459 ]]
Error is [[ 0.]
 [ 0.]
 [ 1.]
 [-1.]] for iteration 13

W is [[-0.35796933  0.5519459 ]]
b is [[-0.35796933  0.5519459 ]]
Error is [[ 0.]
 [ 0.]
 [ 1.]
 [ 0.]] for iteration 305
W is [[-0.35696933  0.5519459 ]]
b is [[-0.35696933  0.5519459 ]]
Error is [[ 0.]
 [ 0.]
 [ 1.]
 [ 0.]] for iteration 306
W is [[-0.35596933  0.5519459 ]]
b is [[-0.35596933  0.5519459 ]]
Error is [[ 0.]
 [ 0.]
 [ 1.]
 [-1.]] for iteration 307
W is [[-0.35596933  0.5509459 ]]
b is [[-0.35596933  0.5509459 ]]
Error is [[ 0.]
 [ 0.]
 [ 1.]
 [ 0.]] for iteration 308
W is [[-0.35496933  0.5509459 ]]
b is [[-0.35496933  0.5509459 ]]
Error is [[ 0.]
 [ 0.]
 [ 1.]
 [ 0.]] for iteration 309
W is [[-0.35396933  0.5509459 ]]
b is [[-0.35396933  0.5509459 ]]
Error is [[ 0.]
 [ 0.]
 [ 1.]
 [-1.]] for iteration 310
W is [[-0.35396933  0.5499459 ]]
b is [[-0.35396933  0.5499459 ]]
Error is [[ 0.]
 [ 0.]
 [ 1.]
 [ 0.]] for iteration 311
W is [[-0.35296933  0.5499459 ]]
b is [[-0.35296933  0.5499459 ]]
Error is [[ 0.]
 [ 0.]
 [ 1.]
 [ 0.]] for iteration 312
W is [[-0.35196933  0.54

 [ 0.]] for iteration 486
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 487
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 488
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 489
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 490
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 491
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 492
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 493
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 49

b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 671
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 672
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 673
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 674
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 675
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 676
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 677
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 678
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.54

W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 822
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 823
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 824
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 825
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 826
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 827
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 828
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 829
W is [[-0.33596933  0.54

Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 987
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 988
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 989
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 990
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 991
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 992
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 993
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] for iteration 994
W is [[-0.33596933  0.5409459 ]]
b is [[-0.33596933  0.5409459 ]]
Error is [[ 0.]
 [ 0.]
 

In [255]:
def model(X,Y,num_iterations,learning_rate):
    W, b = init_weights()
    print ("Initial W is {} and b is {}".format(W,b))
    params = optimize(W,b,X,Y,num_iterations, learning_rate)
    print ("Final W is {} and b is {}".format(params["W"],params["b"]))
    #print W
    #print b
    return params  

print (model(X,Y_AND,3000,0.001))
#print (model(X,Y_AND,1000,0.001))

Initial W is [[ 0.80744016  0.8960913 ]] and b is 0
Final W is [[ 0.40344016  0.4470913 ]] and b is [[ 0.   ]
 [-0.449]
 [-0.404]
 [ 0.   ]]
{'b': array([[ 0.   ],
       [-0.449],
       [-0.404],
       [ 0.   ]]), 'W': array([[ 0.40344016,  0.4470913 ]])}


In [256]:
def validation(params):
    W = params["W"]
    
    b = params["b"]
    W = W.reshape((2,1))
    A = step((np.dot(X,W) + b),0)
    return  A

print validation(model(X,Y_AND,10000,0.001))

Initial W is [[ 0.31800347  0.11005192]] and b is 0
Final W is [[ 0.15800347  0.05405192]] and b is [[ 0.   ]
 [-0.056]
 [-0.16 ]
 [ 0.   ]]
[[ 0.]
 [ 0.]
 [ 0.]
 [ 1.]]
