In [1]:
import numpy as np
import scipy

In [2]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])

Y_AND = np.array([0,0,0,1]).reshape((4,1))
Y_OR = np.array([0,1,1,1]).reshape((4,1))
Y_XOR = np.array([0,1,1,0]).reshape((4,1))

print ("X is \n {} \n its shape is {}". format(X,X.shape))
print ("Y_AND is \n {} \n its shape is {}".format(Y_AND,Y_AND.shape))
print ("Y_OR is \n {} \n its shape is {}".format(Y_OR,Y_OR.shape))
print ("Y_XOR is \n {} \n its shape is {}".format(Y_XOR,Y_XOR.shape))

X is 
 [[0 0]
 [0 1]
 [1 0]
 [1 1]] 
 its shape is (4, 2)
Y_AND is 
 [[0]
 [0]
 [0]
 [1]] 
 its shape is (4, 1)
Y_OR is 
 [[0]
 [1]
 [1]
 [1]] 
 its shape is (4, 1)
Y_XOR is 
 [[0]
 [1]
 [1]
 [0]] 
 its shape is (4, 1)


In [74]:
def init_weights():
    W = np.random.rand(1,2)
    b = 1
    return W, b
#print ("Random weights are initialized as W = {}".format(W))

In [75]:
def step(z):
    return np.heaviside(z,1)

#print step([1, -3, 1, 4.3, -1, 0, 1],1)

In [76]:
def propagate(W,b,X,Y):
    A = step((np.dot(X,W.T) + b))
    Error = Y - A
    return Error

#print(propagate(W,b,X,Y_OR))

In [92]:
def optimize(W,b,X,Y,num_iterations, learning_rate):
    
    for i in range(num_iterations):
        Error = propagate(W,b,X,Y)
        #print ("Error is {} for iteration {}".format(Error, i+1))
        W = W + np.multiply(learning_rate , (np.dot(Error.T,X))) 
        b = b + np.multiply(learning_rate , Error)
    params = {"W" : W, "b" : b}
    return params

#print optimize(W,b,X,Y_OR,100,0.1)       

In [107]:
def model(X,Y,num_iterations,learning_rate):
    W, b = init_weights()
    #print ("Initial W is {} and b is {}".format(W,b))
    params = optimize(W,b,X,Y,num_iterations, learning_rate)
    #print ("Final W is {} and b is {}".format(params["W"],params["b"]))
    print ("W is" ,W)
    print ("b is ",b)
    return params  

print (model(X,Y_XOR,2000,0.001))
#print (model(X,Y_AND,1000,0.001))

('W is', array([[ 0.63877672,  0.29257892]]))
('b is ', 1)
{'b': array([[ -8.81239526e-16],
       [  1.00000000e+00],
       [  1.00000000e+00],
       [  3.56000000e-01]]), 'W': array([[-0.00522328, -0.35142108]])}


In [108]:
def validation(X,params):
    W = params["W"]
    b = params["b"]
    print W
    print b
    A = step((np.dot(X,W.T) + b))
    return  A

In [110]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
validation(X,model(X,Y_XOR,2000,0.1))

('W is', array([[ 0.07584091,  0.49615044]]))
('b is ', 1)
[[-0.52415909 -0.10384956]]
[[-0.1]
 [ 1. ]
 [ 1. ]
 [ 0.4]]


array([[ 0.],
       [ 1.],
       [ 1.],
       [ 0.]])

In [166]:
#


# importing libraries
from random import choice
from numpy import array, dot, random

# heaviside step function 
unit_step = lambda x: 0 if x < 0 else 1


training_data = [
    (array([0,0,1]), 0),
    (array([0,1,1]), 1),
    (array([1,0,1]), 1),
    (array([1,1,1]), 1),
]

w = random.rand(3)

errors = []
eta = 0.2
n = 100

for i in xrange(n):
    x, expected = choice(training_data)
    result = dot(w, x)
    error = expected - unit_step(result)
    errors.append(error)
    
    w += eta * error * x
    

for x, _ in training_data:
    result = dot(x, w)
    print("{}: {} -> {}".format(x[:2], result, unit_step(result)))

[0 0]: -0.073006392609 -> 0
[0 1]: 0.442366524624 -> 1
[1 0]: 0.492394899458 -> 1
[1 1]: 1.00776781669 -> 1
